# Generated by Django 3.2.13 on 2023-04-15 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0002_auto_20230406_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ManyToManyField(to='annotation.APIAnnClasses')),
                ('Group', models.ManyToManyField(to='annotation.APIAnnGroups')),
                ('Lables', models.ManyToManyField(to='annotation.APIAnnLables')),
                ('Weight', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='annotation.annweight')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
