# Generated by Django 3.2.13 on 2023-04-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_annotationobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiannclasses',
            name='color',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='apianngroups',
            name='color',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='apiannlables',
            name='color',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
