# Generated by Django 3.2.13 on 2023-04-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificator', '0008_auto_20230413_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclasses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apigroups',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apilables',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userobjects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
