# Generated by Django 3.2.13 on 2023-04-17 19:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificator', '0009_auto_20230417_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclasses',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='apiclasses',
            name='lables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
    ]
