# Generated by Django 3.2.13 on 2023-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificator', '0011_auto_20230421_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclasses',
            name='parent',
            field=models.CharField(max_length=256),
        ),
    ]
