# Generated by Django 3.2.13 on 2023-05-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificator', '0012_alter_apiclasses_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclasses',
            name='parent',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
