# Generated by Django 3.2.13 on 2023-05-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classificator', '0014_alter_apiclasses_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclasses',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Child_lables', to='classificator.apilables'),
        ),
    ]
