# Generated by Django 3.2.13 on 2023-05-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classificator', '0019_alter_apiclasses_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userobjects',
            old_name='labels',
            new_name='lables',
        ),
    ]
